const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const dataDir = path.join(__dirname, '..', 'sample_data', 'ndjson');
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}

// 1. dim_currencies
const dim_currencies = [
  { currency_code: 'ZAR', currency_name: 'South African Rand', country_code: 'ZA', symbol: 'R', decimal_places: 2, is_active: true, notes: 'Legal tender in South Africa and Common Monetary Area' },
  { currency_code: 'USD', currency_name: 'United States Dollar', country_code: 'US', symbol: '$', decimal_places: 2, is_active: true, notes: 'Dominant currency for pricing and Nostro FCA accounts in Zimbabwe' },
  { currency_code: 'ZiG', currency_name: 'Zimbabwe Gold', country_code: 'ZW', symbol: 'ZiG', decimal_places: 2, is_active: true, notes: 'Structured currency backed by gold and foreign reserves introduced April 2024' },
  { currency_code: 'ZWL', currency_name: 'Zimbabwean Dollar (Historical)', country_code: 'ZW', symbol: 'ZWL$', decimal_places: 2, is_active: false, notes: 'Decommissioned predecessor to ZiG' }
];

// 2. dim_accounts
const dim_accounts = [
  { account_id: 'ACC_ZA_CAPITEC_DAILY', account_name: 'Capitec Primary Cheque', financial_institution: 'Capitec Bank', country_code: 'ZA', primary_currency: 'ZAR', cash_flow_tier: 'DAILY_SPENDING', account_type: 'CHECKING', is_vault_locked: false, withdrawal_notice_days: 0, account_number_masked: '...4091', is_active: true, created_at: '2026-01-01 00:00:00 UTC' },
  { account_id: 'ACC_ZA_FNB_MONTHLY', account_name: 'FNB Monthly Bills Fusion', financial_institution: 'First National Bank', country_code: 'ZA', primary_currency: 'ZAR', cash_flow_tier: 'MONTHLY_ALLOCATION', account_type: 'CHECKING', is_vault_locked: false, withdrawal_notice_days: 0, account_number_masked: '...8812', is_active: true, created_at: '2026-01-01 00:00:00 UTC' },
  { account_id: 'ACC_ZA_DISCOVERY_VAULT', account_name: 'Discovery 32-Day Notice Emergency', financial_institution: 'Discovery Bank', country_code: 'ZA', primary_currency: 'ZAR', cash_flow_tier: 'LONG_TERM_VAULT', account_type: 'SAVINGS', is_vault_locked: true, withdrawal_notice_days: 32, account_number_masked: '...1940', is_active: true, created_at: '2026-01-01 00:00:00 UTC' },
  { account_id: 'ACC_ZA_EE_EQUITIES_VAULT', account_name: 'EasyEquities S&P500 & Top40 TFSA', financial_institution: 'EasyEquities', country_code: 'ZA', primary_currency: 'ZAR', cash_flow_tier: 'LONG_TERM_VAULT', account_type: 'INVESTMENT_BROKER', is_vault_locked: true, withdrawal_notice_days: 999, account_number_masked: '...EE77', is_active: true, created_at: '2026-01-01 00:00:00 UTC' },
  { account_id: 'ACC_ZW_STANBIC_NOSTRO', account_name: 'Stanbic Nostro FCA Bills', financial_institution: 'Stanbic Bank Zimbabwe', country_code: 'ZW', primary_currency: 'USD', cash_flow_tier: 'MONTHLY_ALLOCATION', account_type: 'CHECKING', is_vault_locked: false, withdrawal_notice_days: 0, account_number_masked: '...5521', is_active: true, created_at: '2026-01-01 00:00:00 UTC' },
  { account_id: 'ACC_ZW_ECOCASH_USD', account_name: 'EcoCash USD Wallet', financial_institution: 'EcoCash', country_code: 'ZW', primary_currency: 'USD', cash_flow_tier: 'DAILY_SPENDING', account_type: 'MOBILE_MONEY', is_vault_locked: false, withdrawal_notice_days: 0, account_number_masked: '...0772', is_active: true, created_at: '2026-01-01 00:00:00 UTC' },
  { account_id: 'ACC_ZW_ECOCASH_ZIG', account_name: 'EcoCash ZiG Wallet', financial_institution: 'EcoCash', country_code: 'ZW', primary_currency: 'ZiG', cash_flow_tier: 'DAILY_SPENDING', account_type: 'MOBILE_MONEY', is_vault_locked: false, withdrawal_notice_days: 0, account_number_masked: '...0772', is_active: true, created_at: '2026-01-01 00:00:00 UTC' },
  { account_id: 'ACC_ZW_INNBUCKS_USD', account_name: 'InnBucks USD Pocket', financial_institution: 'InnBucks Microfinance', country_code: 'ZW', primary_currency: 'USD', cash_flow_tier: 'DAILY_SPENDING', account_type: 'MOBILE_MONEY', is_vault_locked: false, withdrawal_notice_days: 0, account_number_masked: '...4311', is_active: true, created_at: '2026-01-01 00:00:00 UTC' },
  { account_id: 'ACC_ZW_OM_UNITTRUST_VAULT', account_name: 'Old Mutual USD Balanced Unit Trust', financial_institution: 'Old Mutual Zimbabwe', country_code: 'ZW', primary_currency: 'USD', cash_flow_tier: 'LONG_TERM_VAULT', account_type: 'INVESTMENT_BROKER', is_vault_locked: true, withdrawal_notice_days: 14, account_number_masked: '...OM09', is_active: true, created_at: '2026-01-01 00:00:00 UTC' }
];

// 3. dim_categories (with Tax Classification)
const dim_categories = [
  // Income
  { category_id: 'CAT_INC_SALARY', category_name: 'Consulting & Employment Income', parent_category_id: null, category_group: 'INCOME', cash_flow_tier: 'MONTHLY_ALLOCATION', is_essential_need: false, is_tax_deductible: false, tax_line_item: 'TAXABLE_GROSS_INCOME', description: 'Primary monthly consulting retainer and professional earnings' },
  { category_id: 'CAT_INC_DIVIDENDS', category_name: 'Investment Dividends', parent_category_id: null, category_group: 'INCOME', cash_flow_tier: 'LONG_TERM_VAULT', is_essential_need: false, is_tax_deductible: false, tax_line_item: 'TAXABLE_INVESTMENT_INCOME', description: 'Quarterly dividends received on ETF holdings' },

  // Daily Spending
  { category_id: 'CAT_DAILY_GROCERIES', category_name: 'Groceries & Household Supplies', parent_category_id: null, category_group: 'LIVING_EXPENSES', cash_flow_tier: 'DAILY_SPENDING', is_essential_need: true, is_tax_deductible: false, tax_line_item: 'NON_DEDUCTIBLE', description: 'Supermarket food and household consumables' },
  { category_id: 'CAT_DAILY_DINING', category_name: 'Restaurants, Takeaways & Coffee', parent_category_id: null, category_group: 'DISCRETIONARY', cash_flow_tier: 'DAILY_SPENDING', is_essential_need: false, is_tax_deductible: false, tax_line_item: 'NON_DEDUCTIBLE', description: 'Eating out, fast food, and barista coffee' },
  { category_id: 'CAT_DAILY_FUEL_TRANS', category_name: 'Fuel, Uber & Commute', parent_category_id: null, category_group: 'LIVING_EXPENSES', cash_flow_tier: 'DAILY_SPENDING', is_essential_need: true, is_tax_deductible: false, tax_line_item: 'NON_DEDUCTIBLE', description: 'Petrol purchases, Uber rides, and local travel' },
  { category_id: 'CAT_DAILY_AIRTIME', category_name: 'Mobile Airtime & Bundles', parent_category_id: null, category_group: 'LIVING_EXPENSES', cash_flow_tier: 'DAILY_SPENDING', is_essential_need: true, is_tax_deductible: false, tax_line_item: 'NON_DEDUCTIBLE', description: 'Data bundles and voice airtime (Vodacom, MTN, Econet)' },
  { category_id: 'CAT_DAILY_INCIDENTAL', category_name: 'Micro-Cash & Incidentals', parent_category_id: null, category_group: 'DISCRETIONARY', cash_flow_tier: 'DAILY_SPENDING', is_essential_need: false, is_tax_deductible: false, tax_line_item: 'NON_DEDUCTIBLE', description: 'Car guard tips, cash petty expenses, minor purchases' },

  // Business Productivity Purchases (Tax-Deductible)
  { category_id: 'CAT_PROD_TECH_HARDWARE', category_name: 'Productivity Tech & Work Hardware', parent_category_id: null, category_group: 'BUSINESS_PRODUCTIVITY', cash_flow_tier: 'DAILY_SPENDING', is_essential_need: false, is_tax_deductible: true, tax_line_item: 'PRODUCTIVITY_HARDWARE', description: 'Computers, displays, work desks, UPS/power, and mobile workstations for productivity' },
  { category_id: 'CAT_PROD_SOFTWARE_TOOLS', category_name: 'Business Software, Cloud & AI Subscriptions', parent_category_id: null, category_group: 'BUSINESS_PRODUCTIVITY', cash_flow_tier: 'MONTHLY_ALLOCATION', is_essential_need: false, is_tax_deductible: true, tax_line_item: 'BUSINESS_SOFTWARE', description: 'AI subscriptions (ChatGPT, Claude), GitHub, cloud infrastructure (GCP, AWS), IDEs, SaaS' },
  { category_id: 'CAT_PROD_PROFESSIONAL_SERVICES', category_name: 'Professional Services & Compliance', parent_category_id: null, category_group: 'BUSINESS_PRODUCTIVITY', cash_flow_tier: 'MONTHLY_ALLOCATION', is_essential_need: false, is_tax_deductible: true, tax_line_item: 'PROFESSIONAL_SERVICES', description: 'Accounting, tax preparation, bookkeeping, legal counsel, and business compliance filings' },

  // Monthly Allocations & Statutory
  { category_id: 'CAT_ALLOC_RENT', category_name: 'Residential Rent & Levies', parent_category_id: null, category_group: 'LIVING_EXPENSES', cash_flow_tier: 'MONTHLY_ALLOCATION', is_essential_need: true, is_tax_deductible: false, tax_line_item: 'NON_DEDUCTIBLE', description: 'Monthly apartment or home rental payment' },
  { category_id: 'CAT_ALLOC_MEDICAL', category_name: 'Medical Aid Scheme', parent_category_id: null, category_group: 'LIVING_EXPENSES', cash_flow_tier: 'MONTHLY_ALLOCATION', is_essential_need: true, is_tax_deductible: false, tax_line_item: 'MEDICAL_TAX_CREDIT', description: 'Discovery Health / Cimas healthcare contribution' },
  { category_id: 'CAT_ALLOC_ELECTRICITY', category_name: 'Pre-paid Power & Utility Tokens', parent_category_id: null, category_group: 'LIVING_EXPENSES', cash_flow_tier: 'MONTHLY_ALLOCATION', is_essential_need: true, is_tax_deductible: false, tax_line_item: 'NON_DEDUCTIBLE', description: 'Eskom power vouchers and ZESA prepaid electricity tokens' },
  { category_id: 'CAT_ALLOC_INTERNET', category_name: 'High-Speed Home Fibre', parent_category_id: null, category_group: 'LIVING_EXPENSES', cash_flow_tier: 'MONTHLY_ALLOCATION', is_essential_need: true, is_tax_deductible: true, tax_line_item: 'HOME_OFFICE_DEDUCTION', description: 'Uncapped home fibre broadband connectivity for work' },
  { category_id: 'CAT_ALLOC_INSURANCE', category_name: 'Short-Term Vehicle & Asset Cover', parent_category_id: null, category_group: 'DEBT_OBLIGATIONS', cash_flow_tier: 'MONTHLY_ALLOCATION', is_essential_need: true, is_tax_deductible: false, tax_line_item: 'NON_DEDUCTIBLE', description: 'Car and contents insurance premium' },
  { category_id: 'CAT_ALLOC_SUBSCRIPTIONS', category_name: 'Digital Subscriptions', parent_category_id: null, category_group: 'DISCRETIONARY', cash_flow_tier: 'MONTHLY_ALLOCATION', is_essential_need: false, is_tax_deductible: false, tax_line_item: 'NON_DEDUCTIBLE', description: 'Entertainment media (Netflix, Spotify)' },
  { category_id: 'CAT_TAX_STATUTORY_PROVISIONAL', category_name: 'Provisional & Statutory Tax Payments', parent_category_id: null, category_group: 'STATUTORY_OBLIGATIONS', cash_flow_tier: 'MONTHLY_ALLOCATION', is_essential_need: true, is_tax_deductible: false, tax_line_item: 'STATUTORY_TAX_PAYMENT', description: 'Provisional tax payments, PAYE top-ups, and corporate statutory remittances to SARS or ZIMRA' },

  // Long-Term Vault
  { category_id: 'CAT_VAULT_EMERGENCY', category_name: 'Liquid Emergency Reserve Fund', parent_category_id: null, category_group: 'VAULT_INVESTMENTS', cash_flow_tier: 'LONG_TERM_VAULT', is_essential_need: true, is_tax_deductible: false, tax_line_item: 'NON_DEDUCTIBLE', description: 'Capital held for unforeseen financial emergencies (32-day notice)' },
  { category_id: 'CAT_VAULT_GLOBAL_ETF', category_name: 'Offshore S&P 500 Index Equities', parent_category_id: null, category_group: 'VAULT_INVESTMENTS', cash_flow_tier: 'LONG_TERM_VAULT', is_essential_need: false, is_tax_deductible: false, tax_line_item: 'CAPITAL_INVESTMENT', description: 'Compounding long-term retirement and passive capital build' },

  // Internal Transfers
  { category_id: 'CAT_INTERNAL_SWEEP', category_name: 'Cross-Tier Capital Allocation Transfer', parent_category_id: null, category_group: 'INTERNAL_TRANSFERS', cash_flow_tier: 'CROSS_TIER_TRANSFER', is_essential_need: false, is_tax_deductible: false, tax_line_item: 'INTERNAL_TRANSFER', description: 'Transfer legs moving money between Daily, Monthly, and Vault' }
];

// 4. fct_exchange_rates
const fct_exchange_rates = [
  { rate_date: '2026-09-01', rate_timestamp: '2026-09-01 07:00:00 UTC', base_currency: 'USD', quote_currency: 'ZAR', rate_type: 'OFFICIAL_INTERBANK', exchange_rate: 18.250000, inverse_rate: 0.054795, source_provider: 'SARB', notes: 'South African Reserve Bank daily closing mid-market rate' },
  { rate_date: '2026-09-01', rate_timestamp: '2026-09-01 07:00:00 UTC', base_currency: 'USD', quote_currency: 'ZAR', rate_type: 'CARD_SETTLEMENT', exchange_rate: 18.615000, inverse_rate: 0.053720, source_provider: 'Visa / MasterCard', notes: 'Retail commercial card swipe foreign transaction rate with 2% margin' },
  { rate_date: '2026-09-01', rate_timestamp: '2026-09-01 07:00:00 UTC', base_currency: 'USD', quote_currency: 'ZiG', rate_type: 'OFFICIAL_INTERBANK', exchange_rate: 13.850000, inverse_rate: 0.072202, source_provider: 'Reserve Bank of Zimbabwe', notes: 'Official interbank weighted exchange rate for ZiG' },
  { rate_date: '2026-09-01', rate_timestamp: '2026-09-01 07:00:00 UTC', base_currency: 'USD', quote_currency: 'ZiG', rate_type: 'MARKET_PARALLEL', exchange_rate: 24.500000, inverse_rate: 0.040816, source_provider: 'ZimMarket Index', notes: 'Alternative street cash rate reflecting open retail trading premium' },
  { rate_date: '2026-09-01', rate_timestamp: '2026-09-01 07:00:00 UTC', base_currency: 'ZAR', quote_currency: 'ZiG', rate_type: 'OFFICIAL_INTERBANK', exchange_rate: 0.758900, inverse_rate: 1.317697, source_provider: 'RBZ Cross Rate', notes: 'Cross rate calculated via official USD mid-point' },
  { rate_date: '2026-09-01', rate_timestamp: '2026-09-01 07:00:00 UTC', base_currency: 'ZAR', quote_currency: 'ZiG', rate_type: 'MARKET_PARALLEL', exchange_rate: 1.342466, inverse_rate: 0.744900, source_provider: 'ZimMarket Index', notes: 'Border cash trading rate at Beitbridge' }
];

// 5. fct_budget_allocations
const fct_budget_allocations = [
  { allocation_month: '2026-09-01', category_id: 'CAT_ALLOC_RENT', cash_flow_tier: 'MONTHLY_ALLOCATION', target_currency: 'ZAR', planned_amount: 14500.0000, planned_amount_usd: 794.5205, planned_amount_zar: 14500.0000, rollover_from_prior: 0.0000, is_fixed_obligation: true, notes: 'Apartment lease debit order' },
  { allocation_month: '2026-09-01', category_id: 'CAT_ALLOC_MEDICAL', cash_flow_tier: 'MONTHLY_ALLOCATION', target_currency: 'ZAR', planned_amount: 3850.0000, planned_amount_usd: 210.9589, planned_amount_zar: 3850.0000, rollover_from_prior: 0.0000, is_fixed_obligation: true, notes: 'Discovery Classic Comprehensive Plan' },
  { allocation_month: '2026-09-01', category_id: 'CAT_ALLOC_ELECTRICITY', cash_flow_tier: 'MONTHLY_ALLOCATION', target_currency: 'ZAR', planned_amount: 1800.0000, planned_amount_usd: 98.6301, planned_amount_zar: 1800.0000, rollover_from_prior: 150.0000, is_fixed_obligation: true, notes: 'Eskom prepaid electricity envelope' },
  { allocation_month: '2026-09-01', category_id: 'CAT_ALLOC_INTERNET', cash_flow_tier: 'MONTHLY_ALLOCATION', target_currency: 'ZAR', planned_amount: 999.0000, planned_amount_usd: 54.7397, planned_amount_zar: 999.0000, rollover_from_prior: 0.0000, is_fixed_obligation: true, notes: 'Openserve 100/50 Fibre debit order (tax deductible home office)' },
  { allocation_month: '2026-09-01', category_id: 'CAT_ALLOC_INSURANCE', cash_flow_tier: 'MONTHLY_ALLOCATION', target_currency: 'ZAR', planned_amount: 1250.0000, planned_amount_usd: 68.4932, planned_amount_zar: 1250.0000, rollover_from_prior: 0.0000, is_fixed_obligation: true, notes: 'Outsurance Comprehensive vehicle cover' },
  { allocation_month: '2026-09-01', category_id: 'CAT_ALLOC_SUBSCRIPTIONS', cash_flow_tier: 'MONTHLY_ALLOCATION', target_currency: 'ZAR', planned_amount: 550.0000, planned_amount_usd: 30.1370, planned_amount_zar: 550.0000, rollover_from_prior: 0.0000, is_fixed_obligation: false, notes: 'Netflix & Spotify family plans' },
  { allocation_month: '2026-09-01', category_id: 'CAT_ALLOC_ELECTRICITY', cash_flow_tier: 'MONTHLY_ALLOCATION', target_currency: 'USD', planned_amount: 120.0000, planned_amount_usd: 120.0000, planned_amount_zar: 2190.0000, rollover_from_prior: 20.0000, is_fixed_obligation: true, notes: 'ZESA token purchase via Nostro card' },
  { allocation_month: '2026-09-01', category_id: 'CAT_DAILY_GROCERIES', cash_flow_tier: 'DAILY_SPENDING', target_currency: 'ZAR', planned_amount: 6500.0000, planned_amount_usd: 356.1644, planned_amount_zar: 6500.0000, rollover_from_prior: 450.0000, is_fixed_obligation: false, notes: 'Woolworths / Checkers grocery envelope' },
  { allocation_month: '2026-09-01', category_id: 'CAT_DAILY_DINING', cash_flow_tier: 'DAILY_SPENDING', target_currency: 'ZAR', planned_amount: 2500.0000, planned_amount_usd: 136.9863, planned_amount_zar: 2500.0000, rollover_from_prior: 0.0000, is_fixed_obligation: false, notes: 'Social dining and takeaways' },
  { allocation_month: '2026-09-01', category_id: 'CAT_DAILY_FUEL_TRANS', cash_flow_tier: 'DAILY_SPENDING', target_currency: 'ZAR', planned_amount: 3000.0000, planned_amount_usd: 164.3836, planned_amount_zar: 3000.0000, rollover_from_prior: 0.0000, is_fixed_obligation: false, notes: 'Petrol allowance' },
  { allocation_month: '2026-09-01', category_id: 'CAT_DAILY_AIRTIME', cash_flow_tier: 'DAILY_SPENDING', target_currency: 'USD', planned_amount: 50.0000, planned_amount_usd: 50.0000, planned_amount_zar: 912.5000, rollover_from_prior: 0.0000, is_fixed_obligation: false, notes: 'EcoCash data bundles' },
  { allocation_month: '2026-09-01', category_id: 'CAT_PROD_SOFTWARE_TOOLS', cash_flow_tier: 'MONTHLY_ALLOCATION', target_currency: 'ZAR', planned_amount: 1500.0000, planned_amount_usd: 82.1918, planned_amount_zar: 1500.0000, rollover_from_prior: 0.0000, is_fixed_obligation: true, notes: 'ChatGPT Team, Claude Pro, and GitHub developer tools' },
  { allocation_month: '2026-09-01', category_id: 'CAT_TAX_STATUTORY_PROVISIONAL', cash_flow_tier: 'MONTHLY_ALLOCATION', target_currency: 'ZAR', planned_amount: 12000.0000, planned_amount_usd: 657.5342, planned_amount_zar: 12000.0000, rollover_from_prior: 0.0000, is_fixed_obligation: true, notes: 'Quarterly provisional tax payment reserve' },
  { allocation_month: '2026-09-01', category_id: 'CAT_VAULT_GLOBAL_ETF', cash_flow_tier: 'LONG_TERM_VAULT', target_currency: 'ZAR', planned_amount: 8000.0000, planned_amount_usd: 438.3562, planned_amount_zar: 8000.0000, rollover_from_prior: 0.0000, is_fixed_obligation: false, notes: 'Target monthly transfer into EasyEquities S&P500' },
  { allocation_month: '2026-09-01', category_id: 'CAT_VAULT_EMERGENCY', cash_flow_tier: 'LONG_TERM_VAULT', target_currency: 'ZAR', planned_amount: 3000.0000, planned_amount_usd: 164.3836, planned_amount_zar: 3000.0000, rollover_from_prior: 0.0000, is_fixed_obligation: false, notes: 'Target top-up for 32-day emergency runway' }
];

// 6. fct_transactions
const fct_transactions = [
  {
    transaction_id: 'TX_ZA_20260901_001',
    transaction_timestamp: '2026-09-01 06:15:00 UTC',
    transaction_date: '2026-09-01',
    local_timezone: 'Africa/Johannesburg',
    local_timestamp: '2026-09-01T08:15:00',
    settlement_timestamp: '2026-09-01 06:15:00 UTC',
    account_id: 'ACC_ZA_FNB_MONTHLY',
    cash_flow_tier: 'MONTHLY_ALLOCATION',
    category_id: 'CAT_INC_SALARY',
    transaction_type: 'INCOME',
    original_amount: 55000.0000,
    original_currency: 'ZAR',
    reporting_amount_usd: 3013.6986,
    reporting_amount_zar: 55000.0000,
    applied_exchange_rate_usd: 0.054795,
    applied_exchange_rate_zar: 1.000000,
    rate_type_applied: 'OFFICIAL_INTERBANK',
    transfer_counterpart_id: null,
    merchant_or_payee: 'Apex Consulting Client Pty Ltd',
    payment_method: 'EFT',
    statutory_levy_or_fee: null,
    is_tax_deductible: false,
    tax_deductible_amount_zar: 0.0000,
    tax_deductible_amount_usd: 0.0000,
    tax_invoice_number: 'INV-2026-089',
    notes: 'Monthly tech consulting retainer fee',
    tags: ['income', 'salary', 'taxable'],
    metadata: { client_ref: 'INV-2026-089' }
  },
  {
    transaction_id: 'TX_ZA_20260901_SWEEP_OUT',
    transaction_timestamp: '2026-09-01 07:00:00 UTC',
    transaction_date: '2026-09-01',
    local_timezone: 'Africa/Johannesburg',
    local_timestamp: '2026-09-01T09:00:00',
    settlement_timestamp: '2026-09-01 07:00:00 UTC',
    account_id: 'ACC_ZA_FNB_MONTHLY',
    cash_flow_tier: 'MONTHLY_ALLOCATION',
    category_id: 'CAT_INTERNAL_SWEEP',
    transaction_type: 'INTERNAL_TRANSFER',
    original_amount: -12000.0000,
    original_currency: 'ZAR',
    reporting_amount_usd: -657.5342,
    reporting_amount_zar: -12000.0000,
    applied_exchange_rate_usd: 0.054795,
    applied_exchange_rate_zar: 1.000000,
    rate_type_applied: 'OFFICIAL_INTERBANK',
    transfer_counterpart_id: 'TX_ZA_20260901_SWEEP_IN',
    merchant_or_payee: 'Capitec Daily Account',
    payment_method: 'EFT',
    statutory_levy_or_fee: 2.5000,
    is_tax_deductible: false,
    tax_deductible_amount_zar: 0.0000,
    tax_deductible_amount_usd: 0.0000,
    tax_invoice_number: null,
    notes: 'Monthly operational allowance transfer to Daily Checking',
    tags: ['transfer', 'daily-allowance'],
    metadata: { eft_type: 'RTC_PAYSHAP' }
  },
  {
    transaction_id: 'TX_ZA_20260901_SWEEP_IN',
    transaction_timestamp: '2026-09-01 07:01:00 UTC',
    transaction_date: '2026-09-01',
    local_timezone: 'Africa/Johannesburg',
    local_timestamp: '2026-09-01T09:01:00',
    settlement_timestamp: '2026-09-01 07:01:00 UTC',
    account_id: 'ACC_ZA_CAPITEC_DAILY',
    cash_flow_tier: 'DAILY_SPENDING',
    category_id: 'CAT_INTERNAL_SWEEP',
    transaction_type: 'INTERNAL_TRANSFER',
    original_amount: 12000.0000,
    original_currency: 'ZAR',
    reporting_amount_usd: 657.5342,
    reporting_amount_zar: 12000.0000,
    applied_exchange_rate_usd: 0.054795,
    applied_exchange_rate_zar: 1.000000,
    rate_type_applied: 'OFFICIAL_INTERBANK',
    transfer_counterpart_id: 'TX_ZA_20260901_SWEEP_OUT',
    merchant_or_payee: 'FNB Monthly Bills Account',
    payment_method: 'EFT',
    statutory_levy_or_fee: null,
    is_tax_deductible: false,
    tax_deductible_amount_zar: 0.0000,
    tax_deductible_amount_usd: 0.0000,
    tax_invoice_number: null,
    notes: 'Inflow from monthly bills sweep',
    tags: ['transfer', 'daily-allowance'],
    metadata: { bank_ref: 'PAYSHAP-FNB-9901' }
  },
  {
    transaction_id: 'TX_ZA_20260901_002',
    transaction_timestamp: '2026-09-01 08:30:00 UTC',
    transaction_date: '2026-09-01',
    local_timezone: 'Africa/Johannesburg',
    local_timestamp: '2026-09-01T10:30:00',
    settlement_timestamp: '2026-09-01 08:30:00 UTC',
    account_id: 'ACC_ZA_FNB_MONTHLY',
    cash_flow_tier: 'MONTHLY_ALLOCATION',
    category_id: 'CAT_ALLOC_RENT',
    transaction_type: 'EXPENSE',
    original_amount: -14500.0000,
    original_currency: 'ZAR',
    reporting_amount_usd: -794.5205,
    reporting_amount_zar: -14500.0000,
    applied_exchange_rate_usd: 0.054795,
    applied_exchange_rate_zar: 1.000000,
    rate_type_applied: 'OFFICIAL_INTERBANK',
    transfer_counterpart_id: null,
    merchant_or_payee: 'Rosebank Central Property Ltd',
    payment_method: 'DIRECT_DEBIT',
    statutory_levy_or_fee: null,
    is_tax_deductible: false,
    tax_deductible_amount_zar: 0.0000,
    tax_deductible_amount_usd: 0.0000,
    tax_invoice_number: 'LEASE-ROSE-202609',
    notes: 'Unit 402 September rental debit order',
    tags: ['fixed-cost', 'rent'],
    metadata: { mandate_id: 'MAND-99120' }
  },
  {
    transaction_id: 'TX_ZA_20260901_003',
    transaction_timestamp: '2026-09-01 09:15:00 UTC',
    transaction_date: '2026-09-01',
    local_timezone: 'Africa/Johannesburg',
    local_timestamp: '2026-09-01T11:15:00',
    settlement_timestamp: '2026-09-01 09:15:00 UTC',
    account_id: 'ACC_ZA_FNB_MONTHLY',
    cash_flow_tier: 'MONTHLY_ALLOCATION',
    category_id: 'CAT_ALLOC_MEDICAL',
    transaction_type: 'EXPENSE',
    original_amount: -3850.0000,
    original_currency: 'ZAR',
    reporting_amount_usd: -210.9589,
    reporting_amount_zar: -3850.0000,
    applied_exchange_rate_usd: 0.054795,
    applied_exchange_rate_zar: 1.000000,
    rate_type_applied: 'OFFICIAL_INTERBANK',
    transfer_counterpart_id: null,
    merchant_or_payee: 'Discovery Health',
    payment_method: 'DIRECT_DEBIT',
    statutory_levy_or_fee: null,
    is_tax_deductible: false,
    tax_deductible_amount_zar: 0.0000,
    tax_deductible_amount_usd: 0.0000,
    tax_invoice_number: 'DH-MEM-9921',
    notes: 'Monthly medical aid contribution debit order',
    tags: ['fixed-cost', 'medical', 'tax-credit'],
    metadata: { policy_no: '992184910' }
  },
  {
    transaction_id: 'TX_ZA_20260901_004',
    transaction_timestamp: '2026-09-01 10:00:00 UTC',
    transaction_date: '2026-09-01',
    local_timezone: 'Africa/Johannesburg',
    local_timestamp: '2026-09-01T12:00:00',
    settlement_timestamp: '2026-09-01 10:00:00 UTC',
    account_id: 'ACC_ZA_FNB_MONTHLY',
    cash_flow_tier: 'MONTHLY_ALLOCATION',
    category_id: 'CAT_ALLOC_INTERNET',
    transaction_type: 'EXPENSE',
    original_amount: -999.0000,
    original_currency: 'ZAR',
    reporting_amount_usd: -54.7397,
    reporting_amount_zar: -999.0000,
    applied_exchange_rate_usd: 0.054795,
    applied_exchange_rate_zar: 1.000000,
    rate_type_applied: 'OFFICIAL_INTERBANK',
    transfer_counterpart_id: null,
    merchant_or_payee: 'Cool Ideas Fibre',
    payment_method: 'DIRECT_DEBIT',
    statutory_levy_or_fee: null,
    is_tax_deductible: true,
    tax_deductible_amount_zar: 999.0000,
    tax_deductible_amount_usd: 54.7397,
    tax_invoice_number: 'INV-CI-2026-09',
    notes: 'Uncapped 100/50 Fibre debit order for remote engineering work',
    tags: ['utilities', 'internet', 'tax-deductible', 'home-office'],
    metadata: { account_num: 'CI-88912' }
  },
  // Tax-Deductible Business Productivity Purchases
  {
    transaction_id: 'TX_ZA_20260902_PROD_001',
    transaction_timestamp: '2026-09-02 11:30:00 UTC',
    transaction_date: '2026-09-02',
    local_timezone: 'Africa/Johannesburg',
    local_timestamp: '2026-09-02T13:30:00',
    settlement_timestamp: '2026-09-02 11:30:00 UTC',
    account_id: 'ACC_ZA_CAPITEC_DAILY',
    cash_flow_tier: 'DAILY_SPENDING',
    category_id: 'CAT_PROD_TECH_HARDWARE',
    transaction_type: 'EXPENSE',
    original_amount: -7500.0000,
    original_currency: 'ZAR',
    reporting_amount_usd: -410.9589,
    reporting_amount_zar: -7500.0000,
    applied_exchange_rate_usd: 0.054795,
    applied_exchange_rate_zar: 1.000000,
    rate_type_applied: 'OFFICIAL_INTERBANK',
    transfer_counterpart_id: null,
    merchant_or_payee: 'Incredible Connection / Dell ZA',
    payment_method: 'DEBIT_CARD',
    statutory_levy_or_fee: null,
    is_tax_deductible: true,
    tax_deductible_amount_zar: 7500.0000,
    tax_deductible_amount_usd: 410.9589,
    tax_invoice_number: 'INV-DELL-9921',
    notes: 'Dell 27-inch 4K USB-C Hub Monitor for engineering workstation',
    tags: ['productivity', 'hardware', 'tax-deductible', 'office-equipment'],
    metadata: { serial_no: 'DL-9921-ZA', asset_tag: 'ASSET-MON-01', tax_year: 2026 }
  },
  {
    transaction_id: 'TX_ZA_20260902_PROD_002',
    transaction_timestamp: '2026-09-02 14:15:00 UTC',
    transaction_date: '2026-09-02',
    local_timezone: 'Africa/Johannesburg',
    local_timestamp: '2026-09-02T16:15:00',
    settlement_timestamp: '2026-09-02 14:15:00 UTC',
    account_id: 'ACC_ZA_CAPITEC_DAILY',
    cash_flow_tier: 'DAILY_SPENDING',
    category_id: 'CAT_PROD_SOFTWARE_TOOLS',
    transaction_type: 'EXPENSE',
    original_amount: -730.0000,
    original_currency: 'ZAR',
    reporting_amount_usd: -40.0000,
    reporting_amount_zar: -730.0000,
    applied_exchange_rate_usd: 0.054795,
    applied_exchange_rate_zar: 1.000000,
    rate_type_applied: 'OFFICIAL_INTERBANK',
    transfer_counterpart_id: null,
    merchant_or_payee: 'Anthropic / OpenAI',
    payment_method: 'DEBIT_CARD',
    statutory_levy_or_fee: null,
    is_tax_deductible: true,
    tax_deductible_amount_zar: 730.0000,
    tax_deductible_amount_usd: 40.0000,
    tax_invoice_number: 'INV-ANTH-312',
    notes: 'Claude Pro and ChatGPT Team subscriptions for coding and data research',
    tags: ['software', 'ai', 'productivity', 'tax-deductible'],
    metadata: { billing_period: '2026-09', tax_year: 2026 }
  },
  // Actual Statutory Tax Payment
  {
    transaction_id: 'TX_ZA_20260903_TAX_001',
    transaction_timestamp: '2026-09-03 09:00:00 UTC',
    transaction_date: '2026-09-03',
    local_timezone: 'Africa/Johannesburg',
    local_timestamp: '2026-09-03T11:00:00',
    settlement_timestamp: '2026-09-03 09:00:00 UTC',
    account_id: 'ACC_ZA_FNB_MONTHLY',
    cash_flow_tier: 'MONTHLY_ALLOCATION',
    category_id: 'CAT_TAX_STATUTORY_PROVISIONAL',
    transaction_type: 'EXPENSE',
    original_amount: -12000.0000,
    original_currency: 'ZAR',
    reporting_amount_usd: -657.5342,
    reporting_amount_zar: -12000.0000,
    applied_exchange_rate_usd: 0.054795,
    applied_exchange_rate_zar: 1.000000,
    rate_type_applied: 'OFFICIAL_INTERBANK',
    transfer_counterpart_id: null,
    merchant_or_payee: 'South African Revenue Service (SARS)',
    payment_method: 'EFT',
    statutory_levy_or_fee: null,
    is_tax_deductible: false,
    tax_deductible_amount_zar: 0.0000,
    tax_deductible_amount_usd: 0.0000,
    tax_invoice_number: 'SARS-PRV-2026-08',
    notes: '2026 First Period Provisional Tax Remittance (IRP6)',
    tags: ['tax', 'provisional-tax', 'sars', 'statutory'],
    metadata: { tax_period: '2026/01', form: 'IRP6', reference: '9812490192' }
  },
  // Vault Transfers & Investments
  {
    transaction_id: 'TX_ZA_20260901_VAULT_ETF',
    transaction_timestamp: '2026-09-01 11:00:00 UTC',
    transaction_date: '2026-09-01',
    local_timezone: 'Africa/Johannesburg',
    local_timestamp: '2026-09-01T13:00:00',
    settlement_timestamp: '2026-09-01 11:00:00 UTC',
    account_id: 'ACC_ZA_EE_EQUITIES_VAULT',
    cash_flow_tier: 'LONG_TERM_VAULT',
    category_id: 'CAT_VAULT_GLOBAL_ETF',
    transaction_type: 'VAULT_CONTRIBUTION',
    original_amount: 8000.0000,
    original_currency: 'ZAR',
    reporting_amount_usd: 438.3562,
    reporting_amount_zar: 8000.0000,
    applied_exchange_rate_usd: 0.054795,
    applied_exchange_rate_zar: 1.000000,
    rate_type_applied: 'OFFICIAL_INTERBANK',
    transfer_counterpart_id: null,
    merchant_or_payee: 'EasyEquities 10X S&P 500 ETF',
    payment_method: 'EFT',
    statutory_levy_or_fee: null,
    is_tax_deductible: false,
    tax_deductible_amount_zar: 0.0000,
    tax_deductible_amount_usd: 0.0000,
    tax_invoice_number: null,
    notes: 'Monthly offshore index capital accumulation',
    tags: ['vault', 'investments', 'etf'],
    metadata: { ticker: 'GLOBAL:SP500', units: 76.41 }
  },
  {
    transaction_id: 'TX_ZA_20260901_VAULT_EMERG',
    transaction_timestamp: '2026-09-01 11:05:00 UTC',
    transaction_date: '2026-09-01',
    local_timezone: 'Africa/Johannesburg',
    local_timestamp: '2026-09-01T13:05:00',
    settlement_timestamp: '2026-09-01 11:05:00 UTC',
    account_id: 'ACC_ZA_DISCOVERY_VAULT',
    cash_flow_tier: 'LONG_TERM_VAULT',
    category_id: 'CAT_VAULT_EMERGENCY',
    transaction_type: 'VAULT_CONTRIBUTION',
    original_amount: 3000.0000,
    original_currency: 'ZAR',
    reporting_amount_usd: 164.3836,
    reporting_amount_zar: 3000.0000,
    applied_exchange_rate_usd: 0.054795,
    applied_exchange_rate_zar: 1.000000,
    rate_type_applied: 'OFFICIAL_INTERBANK',
    transfer_counterpart_id: null,
    merchant_or_payee: 'Discovery 32-Day Notice',
    payment_method: 'EFT',
    statutory_levy_or_fee: null,
    is_tax_deductible: false,
    tax_deductible_amount_zar: 0.0000,
    tax_deductible_amount_usd: 0.0000,
    tax_invoice_number: null,
    notes: 'Emergency buffer maintenance top-up',
    tags: ['vault', 'emergency-fund'],
    metadata: { interest_rate_tier: 'PRIME-0.5' }
  },
  // Operational Daily Spend
  {
    transaction_id: 'TX_ZA_20260901_005',
    transaction_timestamp: '2026-09-01 12:45:00 UTC',
    transaction_date: '2026-09-01',
    local_timezone: 'Africa/Johannesburg',
    local_timestamp: '2026-09-01T14:45:00',
    settlement_timestamp: '2026-09-01 12:45:00 UTC',
    account_id: 'ACC_ZA_CAPITEC_DAILY',
    cash_flow_tier: 'DAILY_SPENDING',
    category_id: 'CAT_DAILY_GROCERIES',
    transaction_type: 'EXPENSE',
    original_amount: -1845.5000,
    original_currency: 'ZAR',
    reporting_amount_usd: -101.1233,
    reporting_amount_zar: -1845.5000,
    applied_exchange_rate_usd: 0.054795,
    applied_exchange_rate_zar: 1.000000,
    rate_type_applied: 'OFFICIAL_INTERBANK',
    transfer_counterpart_id: null,
    merchant_or_payee: 'Woolworths Food Sandton',
    payment_method: 'DEBIT_CARD',
    statutory_levy_or_fee: null,
    is_tax_deductible: false,
    tax_deductible_amount_zar: 0.0000,
    tax_deductible_amount_usd: 0.0000,
    tax_invoice_number: null,
    notes: 'Weekly household pantry and produce replenishment',
    tags: ['groceries', 'food'],
    metadata: { card_last4: '4091', store_id: 'WW-049' }
  },
  {
    transaction_id: 'TX_ZA_20260901_006',
    transaction_timestamp: '2026-09-01 13:20:00 UTC',
    transaction_date: '2026-09-01',
    local_timezone: 'Africa/Johannesburg',
    local_timestamp: '2026-09-01T15:20:00',
    settlement_timestamp: '2026-09-01 13:20:00 UTC',
    account_id: 'ACC_ZA_CAPITEC_DAILY',
    cash_flow_tier: 'DAILY_SPENDING',
    category_id: 'CAT_DAILY_DINING',
    transaction_type: 'EXPENSE',
    original_amount: -251.3750,
    original_currency: 'ZAR',
    reporting_amount_usd: -13.7740,
    reporting_amount_zar: -251.3750,
    applied_exchange_rate_usd: 0.054795,
    applied_exchange_rate_zar: 1.000000,
    rate_type_applied: 'OFFICIAL_INTERBANK',
    transfer_counterpart_id: null,
    merchant_or_payee: 'Tasha\'s Cafe Rosebank',
    payment_method: 'DEBIT_CARD',
    statutory_levy_or_fee: null,
    is_tax_deductible: false,
    tax_deductible_amount_zar: 0.0000,
    tax_deductible_amount_usd: 0.0000,
    tax_invoice_number: null,
    notes: 'Business lunch and cappuccino',
    tags: ['dining', 'coffee'],
    metadata: { receipt_no: 'TSH-8821' }
  },
  {
    transaction_id: 'TX_ZA_20260902_001',
    transaction_timestamp: '2026-09-02 05:40:00 UTC',
    transaction_date: '2026-09-02',
    local_timezone: 'Africa/Johannesburg',
    local_timestamp: '2026-09-02T07:40:00',
    settlement_timestamp: '2026-09-02 05:40:00 UTC',
    account_id: 'ACC_ZA_CAPITEC_DAILY',
    cash_flow_tier: 'DAILY_SPENDING',
    category_id: 'CAT_DAILY_FUEL_TRANS',
    transaction_type: 'EXPENSE',
    original_amount: -950.0000,
    original_currency: 'ZAR',
    reporting_amount_usd: -52.0553,
    reporting_amount_zar: -950.0000,
    applied_exchange_rate_usd: 0.054795,
    applied_exchange_rate_zar: 1.000000,
    rate_type_applied: 'OFFICIAL_INTERBANK',
    transfer_counterpart_id: null,
    merchant_or_payee: 'Shell Jan Smuts',
    payment_method: 'DEBIT_CARD',
    statutory_levy_or_fee: null,
    is_tax_deductible: false,
    tax_deductible_amount_zar: 0.0000,
    tax_deductible_amount_usd: 0.0000,
    tax_invoice_number: null,
    notes: 'Full tank unleaded 95 petrol',
    tags: ['commute', 'petrol'],
    metadata: { litres: 41.3 }
  },
  // Zimbabwean Transactions (USD & ZiG)
  {
    transaction_id: 'TX_ZW_20260902_002',
    transaction_timestamp: '2026-09-02 08:30:00 UTC',
    transaction_date: '2026-09-02',
    local_timezone: 'Africa/Harare',
    local_timestamp: '2026-09-02T10:30:00',
    settlement_timestamp: '2026-09-02 08:30:00 UTC',
    account_id: 'ACC_ZW_ECOCASH_USD',
    cash_flow_tier: 'DAILY_SPENDING',
    category_id: 'CAT_DAILY_GROCERIES',
    transaction_type: 'EXPENSE',
    original_amount: -120.0000,
    original_currency: 'USD',
    reporting_amount_usd: -120.0000,
    reporting_amount_zar: -2190.0000,
    applied_exchange_rate_usd: 1.000000,
    applied_exchange_rate_zar: 18.250000,
    rate_type_applied: 'OFFICIAL_INTERBANK',
    transfer_counterpart_id: null,
    merchant_or_payee: 'OK Mart Chitungwiza',
    payment_method: 'MOBILE_MONEY_ECOCASH',
    statutory_levy_or_fee: 2.4000,
    is_tax_deductible: false,
    tax_deductible_amount_zar: 0.0000,
    tax_deductible_amount_usd: 0.0000,
    tax_invoice_number: null,
    notes: 'Bulk groceries for family residence',
    tags: ['groceries', 'usd-cash'],
    metadata: { ecocash_txn_id: 'MP260902.1030.A10029' }
  },
  {
    transaction_id: 'TX_ZW_20260902_003',
    transaction_timestamp: '2026-09-02 11:10:00 UTC',
    transaction_date: '2026-09-02',
    local_timezone: 'Africa/Harare',
    local_timestamp: '2026-09-02T13:10:00',
    settlement_timestamp: '2026-09-02 11:10:00 UTC',
    account_id: 'ACC_ZW_ECOCASH_ZIG',
    cash_flow_tier: 'DAILY_SPENDING',
    category_id: 'CAT_DAILY_AIRTIME',
    transaction_type: 'EXPENSE',
    original_amount: -245.0000,
    original_currency: 'ZiG',
    reporting_amount_usd: -10.0000,
    reporting_amount_zar: -182.5000,
    applied_exchange_rate_usd: 0.040816,
    applied_exchange_rate_zar: 0.744900,
    rate_type_applied: 'MARKET_PARALLEL',
    transfer_counterpart_id: null,
    merchant_or_payee: 'Econet Airtime Portal',
    payment_method: 'MOBILE_MONEY_ECOCASH',
    statutory_levy_or_fee: 4.9000,
    is_tax_deductible: false,
    tax_deductible_amount_zar: 0.0000,
    tax_deductible_amount_usd: 0.0000,
    tax_invoice_number: null,
    notes: 'SmartBiz monthly data bundle recharge',
    tags: ['airtime', 'data', 'zig'],
    metadata: { bundle_type: 'MONTHLY_50GB' }
  },
  {
    transaction_id: 'TX_ZW_20260902_004',
    transaction_timestamp: '2026-09-02 15:00:00 UTC',
    transaction_date: '2026-09-02',
    local_timezone: 'Africa/Harare',
    local_timestamp: '2026-09-02T17:00:00',
    settlement_timestamp: '2026-09-02 15:00:00 UTC',
    account_id: 'ACC_ZW_STANBIC_NOSTRO',
    cash_flow_tier: 'MONTHLY_ALLOCATION',
    category_id: 'CAT_ALLOC_ELECTRICITY',
    transaction_type: 'EXPENSE',
    original_amount: -100.0000,
    original_currency: 'USD',
    reporting_amount_usd: -100.0000,
    reporting_amount_zar: -1825.0000,
    applied_exchange_rate_usd: 1.000000,
    applied_exchange_rate_zar: 18.250000,
    rate_type_applied: 'OFFICIAL_INTERBANK',
    transfer_counterpart_id: null,
    merchant_or_payee: 'ZETDC / ZESA Power Distribution',
    payment_method: 'DEBIT_CARD',
    statutory_levy_or_fee: 2.0000,
    is_tax_deductible: false,
    tax_deductible_amount_zar: 0.0000,
    tax_deductible_amount_usd: 0.0000,
    tax_invoice_number: null,
    notes: 'Prepaid power token 350 kWh for Harare residence',
    tags: ['utilities', 'electricity'],
    metadata: { token: '4920-1928-3819-4829-1029', kwh: 350.2 }
  },
  {
    transaction_id: 'TX_ZW_20260902_005',
    transaction_timestamp: '2026-09-02 18:30:00 UTC',
    transaction_date: '2026-09-02',
    local_timezone: 'Africa/Harare',
    local_timestamp: '2026-09-02T20:30:00',
    settlement_timestamp: '2026-09-02 18:30:00 UTC',
    account_id: 'ACC_ZW_OM_UNITTRUST_VAULT',
    cash_flow_tier: 'LONG_TERM_VAULT',
    category_id: 'CAT_VAULT_GLOBAL_ETF',
    transaction_type: 'VAULT_CONTRIBUTION',
    original_amount: 250.0000,
    original_currency: 'USD',
    reporting_amount_usd: 250.0000,
    reporting_amount_zar: 4562.5000,
    applied_exchange_rate_usd: 1.000000,
    applied_exchange_rate_zar: 18.250000,
    rate_type_applied: 'OFFICIAL_INTERBANK',
    transfer_counterpart_id: null,
    merchant_or_payee: 'Old Mutual Unit Trust Allocation',
    payment_method: 'EFT',
    statutory_levy_or_fee: null,
    is_tax_deductible: false,
    tax_deductible_amount_zar: 0.0000,
    tax_deductible_amount_usd: 0.0000,
    tax_invoice_number: null,
    notes: 'Offshore balanced fund accumulation deposit',
    tags: ['vault', 'investments'],
    metadata: { nav_per_unit: 1.452, units_added: 172.17 }
  }
];

function writeNdjson(filename, items) {
  const filePath = path.join(dataDir, filename);
  const content = items.map(item => JSON.stringify(item)).join('\n') + '\n';
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`Wrote ${items.length} records to ${filename}`);
}

writeNdjson('dim_currencies.json', dim_currencies);
writeNdjson('dim_accounts.json', dim_accounts);
writeNdjson('dim_categories.json', dim_categories);
writeNdjson('fct_exchange_rates.json', fct_exchange_rates);
writeNdjson('fct_budget_allocations.json', fct_budget_allocations);
writeNdjson('fct_transactions.json', fct_transactions);

console.log('All NDJSON files successfully generated in', dataDir);
